export default {
    API_URL: 'http://localhost:3003/api',
    OAPI_URL: 'http://localhost:3003/oapi',
    USER_KEY: '_textNarrative_user',
    TOKEN_VALIDATED: 'TOKEN_VALIDATED',
    USER_FETCHED: 'USER_FETCHED',
    USER_RESET: 'USER_RESET',
    PUBLIC_HISTORYS_FETCHED: 'PUBLIC_HISTORYS_FETCHED',
    MY_HISTORYS_FETCHED: 'MY_HISTORYS_FETCHED',
    HISTORY_FETCHED: 'HISTORY_FETCHED',
    HISTORYS_SEARCHED: 'HISTORYS_SEARCHED',
    SET_CREATED: 'SET_CREATED',
    SET_LIKE: 'SET_LIKE',
    SEARCH: 'SEARCH',
    GET_PUBLIC_HISTORYS: 'getPublicHistorys',
    GET_MY_HISTORYS: 'getMyHistorys',
    SEARCH_HISTORY: 'searchHistory',
    MY_ALTERNATIVE_TEXT_FETCHED: 'MY_ALTERNATIVE_TEXT_FETCHED'
}